<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE beans [
    <!--定义元素根节点 * 一个或多个 -->
    <!ELEMENT beans (bean*)>
    <!--定义元素bean子节点 * 一个或多个 -->
    <!ELEMENT bean (property*)>
    <!--定义元素property节点 类型为字符串 -->
    <!ELEMENT property (#PCDATA)>
    <!--定义节点上的属性-->
    <!ATTLIST bean id ID #REQUIRED>
    <!ATTLIST bean class CDATA #REQUIRED>
    <!ATTLIST property name CDATA #REQUIRED>
    <!ATTLIST property ref IDREF #REQUIRED>
]>

<beans>
    <!--1. DAO配置 -->
    <bean id="userBasicDao" class="com.muxia.qqzone.dao.impl.UserBasicDaoImpl"/>
    <bean id="topicDao" class="com.muxia.qqzone.dao.impl.TopicDaoImpl"/>
    <bean id="replyDao" class="com.muxia.qqzone.dao.impl.ReplyDaoImpl"/>
    <bean id="hostReplyDao" class="com.muxia.qqzone.dao.impl.HostReplyDaoImpl"/>
    <!--2. Service配置 -->
    <bean id="userBasicService" class="com.muxia.qqzone.service.impl.UserBasicServiceImpl">
        <property name="userBasicDao" ref="userBasicDao"/>
    </bean>
    <bean id="hostReplyService" class="com.muxia.qqzone.service.impl.HostReplyServiceImpl">
        <property name="hostReplyDao" ref="hostReplyDao"/>
    </bean>
    <bean id="replyService" class="com.muxia.qqzone.service.impl.ReplyServiceImpl">
        <property name="replyDao" ref="replyDao"/>
        <property name="userBasicDao" ref="userBasicDao"/>
        <property name="hostReplyService" ref="hostReplyService"/>
    </bean>
    <bean id="topicService" class="com.muxia.qqzone.service.impl.TopicServiceImpl">
        <property name="topicDao" ref="topicDao"/>
        <property name="userBasicService" ref="userBasicService"/>
        <property name="replyService" ref="replyService"/>
    </bean>

    <!--3. Controller配置 -->
    <bean id="user" class="com.muxia.qqzone.controller.UserController">
        <property name="userBasicService" ref="userBasicService"/>
        <property name="topicService" ref="topicService"/>
    </bean>
    <bean id="topic" class="com.muxia.qqzone.controller.TopicController">
        <property name="userBasicService" ref="userBasicService"/>
        <property name="topicService" ref="topicService"/>
    </bean>
    <bean id="reply" class="com.muxia.qqzone.controller.ReplyController">
        <property name="replyService" ref="replyService"/>
    </bean>
    <bean id="hostReply" class="com.muxia.qqzone.controller.HostReplyController">
        <property name="hostReplyService" ref="hostReplyService"/>
    </bean>
</beans>